### ISSUE TITLE
Doku Bauanleitung von vz200 nach vz200-remake portieren

### ISSUE THREAD

**Issue by cwahlmann** [cwahlmann/vz200-remake#11]
Die Dokumentation der Bauanleitung im Repo vz200 soll nach vz200-remake portiert werden. 

- Doku Software-Installation und Emulator-Dokumentation sollen in vz200 verbleiben, bis die Arbeiten am Emulator abgeschlossen sind

- [x] Text und Bilder ins öffentliche Repo verschieben
- [x] Texte ggf. sprachlich überarbeiten
- [x] Texte ggf. auf mehrere Dateien aufteilen
- [x] Englische Übersetzung

**Comment by cwahlmann** [comment]
Kannst du hiermit vielleicht schon mal anfangen? Wenn ich den Rest-Service des Emulators fertig und eingecheckt habe, und du dann mit der Companion-App dran wärst, könnte ich hier weitermachen.

**Comment by kashban** [comment]
Ja, mache ich im Laufe des Wochenendes.

**Comment by cwahlmann** [comment]
Hi! Unter "Platinendesign und -produktion" sind zwei Bilder kaputt.

**Comment by kashban** [comment]
Ist behoben

**Comment by cwahlmann** [comment]
Ich mach mal weiter und teile die Dokumentation in Unterkapitel auf

**Comment by kashban** [comment]
Ich bin an der Übersetzung dran.

**Comment by kashban** [comment]
Ist übersetzt.
